### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by Fladinator666** [Bettman66/wiobrowser#1]
Diese Meldung kommt bei mir, wenn ich „wioNoweb.exe v1.1.2“ ausführen möchte. Betriebssystem Win10 Pro 21H2 (sehr frisch installiert). Auf mein zweiten Pc kommt diese Meldung nicht und funktioniert einwandfrei (auch Win10 Pro 21H2). 
Das seltsame ist, dass die Meldung nicht kommt, wenn ich den ersten Pc mit dem zweiten Pc über Remotedesktop steuere und die wioNoweb.exe ausführe. Beim Trennen der Remotedesktopverbindung wird wioNoweb.exe automatisch geschlossen. 
Wie gesagt das Windows beim ersten Pc ist sehr frisch und nur alle Windows Updates gemacht.  OK drücken bringt nichts. Meldung kommt wieder und .exe wird geschlossen. 

![Screenshot (1)](https://user-images.githubusercontent.com/55363702/153079539-f8cf2fe6-672a-4fe0-8db9-f7b5957f00c4.png)

**Comment by Bettman66** [comment]
Da kann ich jetzt nicht viel mit anfangen, hast du schon Verbindung zum ioBroker wenn die Meldung kommt ?

**Comment by Fladinator666** [comment]
Nein. Kann ja gar keine Verbindung herstellen wenn die .exe sich nicht ausführen lässt bzw. sich selber wieder schließt.

**Comment by Bettman66** [comment]
Kann es sein das die App doppelt ausgeführt wird ?
Die Noweb App braucht nichts zusätzlich, hat mit der neuen Installation nichts zu tun.

**Comment by Fladinator666** [comment]
Im Task-Manager oder bei Autostart ist sie nicht. Wenn ich ich sie öffne wird der Adapter bei iob kurz grün. Dann kommt die  Meldung und die App schließt sich von alleine. Was ich halt  nicht verstehe, ist wenn ich den Pc über Remote steuere kann ich die App starten und die Meldung kommt nicht. Glaube auch nicht das es unbedingt ein Problem von der App ist, weil auf mein  anderen Pc funktioniert es ohne Probleme.

**Comment by Bettman66** [comment]
Hast du beim Starten der App die Windowsmeldung mit dem Port freischalten bekommen und bestätigt ?
Das wäre noch das Einzige was mir einfallen würde.

**Comment by Fladinator666** [comment]
Nur die Meldung und hab Zugriff zugelassen. Hab Pc auch mal vom Netzwerk getrennt und versucht (ohne Erfolg). Ich probiere mal noch bisschen rum. Vielleicht habe ich  ja Erfolg  :)

![Unbenannt](https://user-images.githubusercontent.com/55363702/153094489-0584dc38-0a29-4b00-b5a9-a937b1c3edbd.PNG)
